/* KITE - Kernel Injection and Trampoline Engine */
/* Copyright (C) 2026 Dere3046 */
/* SPDX-License-Identifier: GPL-2.0 */

.section .transit0.text, "ax"
.global _transit0_end
_transit0_end:
    ret

.section .transit4.text, "ax"
.global _transit4_end
_transit4_end:
    ret

.section .transit8.text, "ax"
.global _transit8_end
_transit8_end:
    ret

.section .transit12.text, "ax"
.global _transit12_end
_transit12_end:
    ret
